[package]
name = "caesar"
version = "1.0.8"
edition = "2021"

[dependencies]
dioxus = { version = "0.2.3", features = ["web"] }
nrot = "2.0.0"

[dev-dependencies]
# git hooks
cargo-husky = { version = "1", features = ["user-hooks"] }
